<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAngXJac\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAngXJac/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAngXJac.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAngXJac\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAngXJac\App_KernelDevDebugContainer([
    'container.build_hash' => 'AngXJac',
    'container.build_id' => '9cf841c4',
    'container.build_time' => 1678869903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAngXJac');
